"""Words developers build identifiers and file names from. Generated, do not edit.

Generated by tools/build_code_words.py from the identifiers of the Python 3.12.4
standard library (2476 words, each in at least 3 modules). The file-name
detector never takes them for a given or family name.
"""

CODE_WORDS = frozenset("""
    abbr abc abort aborted abs absolute abspath abstract abstractmethod abstractmethods accept accepted access
    aclose acquire action actions activate active actual adapter adapters add addcomponent added addinfourl
    additional addr address addresses addrs adjust aenter aexit after aiter aix algorithm alias aliases align
    alignment alive all allocate allow allowed almost alpn already alt alternates alternative alternatives
    altsep always amount aname anchor and anext angle ann annotated annotation annotations answer any app
    append appendleft application apply arc archive arcname arcs arg argcount arglist argparse args argument
    arguments argv array ascii assert assertion assign ast astimezone async asyncgens asyncio atexit atime
    atom atomic attach attr attrgetter attribute attributes attrname attrs audit auth authentication
    authenticators authkey author auto avail available await awaitable aware back backlog backup backward bad
    banner bare barrier base basedir basename bases basic basics bbox before begin beginning bell best bgcolor
    bin binary binascii bind binding bisect bit bitmap bits blank block blocked blocking blocks blocksize body
    bom bool boolean bootstrap borderwidth both bottom bound boundary bounded box branch break broadcast
    broken browser btn buf buffer buffered buffering buflen bufsize build builder builtin builtins busy button
    bye byte bytearray bytecode byteorder bytes cache cached caches calc calcsize calculate calendar call
    callable callback callbacks called caller callers calls can cancel cancelled cancelling candidate cannot
    canonical canonname canvas capitalize caps capture cascade case casefold cases cast catch category cause
    cdata ceil cell center certificate cfg cfile cget chain challenge change changed changes char character
    characters charbuffertype charmap chars charset chdir check checkbutton checkcache checked checks child
    children chmod choice choices chown chr chrome chunk chunkname chunks chunksize circle class classes
    classify classmethod clean cleandoc cleanup cleanups clear clearscreen client clock clone close closed
    closefd closing closure cls clsname cmd cmdline cmdloop cmp cnf cnfmerge cnt code codec codecs codes
    codeset col collapse collect collected collections colno colon color colormode column columnconfigure
    columns combine comma command commands comment comments commit common commondialog commonpath commonprefix
    communicate comp compact compare comparison compat compatible compile compiler complete completed
    completer completion complex compname component components compress compressed compression compresslevel
    compressobj compressor comps comptype concurrent cond condition conditional config configure conflict
    confstr conn connect connected connection connlost console const constant constants constructor consts
    consumed consuming cont container containing contains content contents context contextlib contextmanager
    contexts contextvars continuation continue control controller conv conversion convert converter converters
    cookie coord coords copy copyfile copyfileobj copymode copyreg copyright coro coroutine coroutines cos
    count counter counts cpu cram crc cre creat create created credentials credits critical crlf csock css cte
    ctime ctrl ctx ctype ctypes cur curdir curr current curses cursor custom cut cwd daemon dangling data
    dataclass dataclasses datagram datalength datawritten date datetime day days dbm deadline debug debugging
    debuglevel dec decimal decl declaration declarations declared decode decodebytes decoded decoder
    decodestring decoding decomp decompress decompressobj decompressor decorator dedent deep deepcopy def
    default defaultdict defaults defect defects deflated defpath del delattr delay delete deleted delim
    delimiter delitem delta demo denominator deprecated deprecation depth deque desc description descriptions
    descriptor dest destination destroy detach details detect dev device devnull dfas dgram dialog dict
    dictionary dicts diff difference difflib dig digest digit digits dir direction directories directory
    dirlist dirname dirnames dirpath dirs dis disable disabled discard disconnected discover disp dispatch
    dispatcher display disposition dist distance div division divmod doc docstring docstrings doctest doctype
    document does dollar dom domain domains done dont dot dotall dots dotted double doublestar down drain
    drive driver drv dst dtd dummy dump dumps dunder dup duplex duplicate duration durations dynamic eagain
    eager early ebadf echo edit eexist effective einval elapsed elem element elements elif ellipsis else elt
    email embedded emit empty emptystring enable enabled enc encode encodebytes encoded encoder encoders
    encoding encodings encrypted end endheaders endmarker endpos endswith endtime enoent enotconn ensure ent
    enter entered entities entity entries entry enum enumerate env environ environment eof eol epilog epilogue
    epipe epoch equal err errcode errmsg errno error errors errortoken esc escape escapes etype eval event
    events exact example exc except excepthook exception exceptions excl exclude exclusive exe exec executable
    execute executor exist existing exists exit exitcode exited exiting exitmsg exitpriority exp expand
    expandtabs expanduser expandvars expat expect expected expired explain explicit exponent expr ext extend
    extended extension extensions external extra extract extractall extras extsep factor factory fail failed
    failfast failure failures fallback false families family fancy fast fatal fcntl fdopen fds feature
    features feed fetch fget field fields file filemode filename filenames fileno fileobj filepath files fill
    fillcolor filter filterfalse filters filterwarnings final finalize finalizer finally find findall finder
    finditer findlinestarts finish finished first firstlineno fix fixed fixer fixers fixes fixoptions
    fixresult fixup flag flags flatten flist float floor floordiv flow flush fmt fname fnmatch focus fold
    folded follow font for force forever forget fork forking forkserver form format formatdate formats
    formatted formatter formatvalue forward found frac fraction fragment frame framerate frames framesize
    framework free freeze from fromfd fromhex fromkeys fromlist fromtimestamp frozen frozenset fsdecode
    fsencode fset fsize fspath fstat fstring ftp ftruncate full fullmatch fullname fullpath fun func funcname
    funcs function functions functools funny fut future futures fws gap gather gcd gen generate generator
    generic geometry get getaddrinfo getattr getattribute getboolean getbuffer getcodec getcompname
    getcomptype getcwd getdoc getencoding getenv getfd getfilesystemencoding getfp getfqdn getframe
    getframemodulename getframerate getgrnam gethostbyname gethostname getint getints getitem getline getlines
    getmark getmarkers getmembers getmodule getmodulename getmro getmtime getname getnchannels getnewargs
    getnframes getopt getparams getpass getpeername getpid getpwnam getpwuid getrandbits getregentry getresp
    getresponse getsampwidth getscreen getsignal getsize getsockname getsockopt getstate getter getters
    gettext gettimeout getuid geturl getvalue getwelcome gid given glob global globals globs gmtime gmtoff gnu
    got goto grab grammar greater grey grid group groupdict grouped groupindex grouping groups grp guard guess
    gzip had half handle handler handlers handles handshake has hasattr hash hashable hashlib have hdr hdrs
    head header headers heading heap heapify heappop heappush heapq height help helper helpers here hex
    hexdigest hexdigits hidden hide hideturtle high highest hint hints hits hkey hmac holder home hook hooks
    horizontal host hostname hosts hour hours how html http https huge iadd iand icon iconname ident
    identifier identity idle idletasks ids idx ign ignorable ignore ignorecase ignored ilabel illegal imag
    image immutable imp impl implementation implemented implicit import imported importer importlib imports
    imul inc include includes incomplete increment incremental incrementaldecoder incrementalencoder indent
    indentation indented indents index indicator indices inet inf infile infinite info information infos
    inherit inheritable inherited init initargs initfp initial initialized initializer inline inner ino input
    insert insort inspect inst install instance instancecheck instruction instructions int integer integral
    interact interactive interleave intern internal interp interpreter interrupt interrupted intersection
    interspersed interval into inv invalid invalidate invalidation invariant invert inverted invoke ior
    ipaddress ipproto ipv isabs isabstractmethod isalnum isalpha isascii isatty isawaitable isblk ischr
    isclass iscode iscoroutine iscoroutinefunction isdatadescriptor isdigit isdir isdisjoint isdst isfifo
    isfile isframe isfunction isfuture isidentifier isinstance isjunction iskeyword isleap islice islink islnk
    ismethod ismethoddescriptor ismethodwrapper ismodule ismount iso isolated ispkg isreg isroutine issock
    isspace issubclass issuperset istraceback isub isupper item itemgetter items itemsize iter iterable
    iterables iterating iteration iterator iterdir iterencode itertools ixor join joinable joinpath json jump
    junk keep keepends key keyboard keys keyword keywords kill kind klass known kwarg kwargs kwd kwds kwlist
    kwonlyargcount label labels laddr lambda lang language large last lastcmd lasti lastline later launch lazy
    lbrace leader leading leaf leave leaves left leftover legacy legal len length lengths less letters level
    lexists lib library like limit limits line linear linecache lineno lines linesep link list listbox listdir
    listen listener lists literal literals ljust lno lnum load loader loads loc local locale localname locals
    localtime location locations locator lock locked locks log logger logging login long longest longlong
    lookup loop lost low lower lpar lru lseek lshift lst lstat lstrip lzma mac machine machinery made magic
    mailbox main mainloop maintype major make makedirs makefile maketrans manager mangle map mapping maps
    margin mark marker markers marshal mask master match matcher matches matching math max maximum maxlen
    maxline maxlinelen maxrepeat maxsize maxsplit maxvalue maxyear maybe mbc mcls mean media mem member
    members memo memory memoryview menu menubutton merge message meta metaclass metadata metavar meth method
    methodname methods microsecond microseconds mid mime mimetypes min minimum minor minsize minus minute
    minutes misc missing mixed mixin mixins mkdir mkstemp mktemp mktime mmap mod mode model modes modification
    modified modify modname mods module modules modulus mon monotonic month monthname months more most mount
    move moveto mro msg msvcrt mtime mul multi multibyte multibytecodec multiline multipart multiple
    multiprocess multiprocessing mutable mutex mutually name named namedtuple namelist names namespace
    namespaces nametowidget nan nargs native nbytes nchannels ndiff ndigits nearest need needed needs neg
    negate negated negative nested netloc netrc new newargs newline newlines newpos newvalue next nextchar
    nframes nframeswritten ngettext nil nlargest nmpwait node nodelay nodes non none nonlocal nonmultipart
    noop norm normal normalize normcase normpath not notation note notequal notify notset now nowait nul null
    num number numbers numerator numeric obj objclass object objects off offset offsets old once one onerror
    onkey only opaque opcode opcodes open opened opener openssl operation operator opmap opname ops opt
    optimization optimize optimized option optional options optparse opts ord order ordered ordering orig
    origin original osfhandle osx other out outcome outfile output over overflow overlapped override owned
    owner pack package packages pad padded padding padx page pages pair pairs paned param parameter parameters
    params pardir paren parent parenthesize parents parse parsed parsedate parseline parser parsers parsestr
    parsing part partial partialmethod parties partition parts pass passfds passive passwd password pat patch
    patchheader patcomp path pathlib pathname paths pathsep pattern patterns pause paused payload peek pen
    pencolor pending pendown pensize penup per percent perf perm permission pformat pgen phrase pickle pickler
    pickling pid pieces pipe pkg pkgutil place plain platform plen plist plural plus point pointer policy
    policybase poll poly pool pop popen popitem popleft port pos position positional positions posix posixpath
    posonlyargcount possibilities possible post pow power pprint pre preamble prec precision predicate
    preferred prefix prefixed prefixes preformat prep preparation prepare prepend present preserve prev
    previous print printable printer prio priority probably proc process processed processes processing
    product profile prog progname program prompt prop propagate properties property proto protocol protocols
    proxy pseudo pthread public punctuation pure purpose push put putcmd putheader putline putrequest pwd pyc
    pydoc pygram python pytree qname qnames qsize qualname query queue queues quiet quit quopri quoprimime
    quote quoted quotes quotetabs radd radiobutton radius raise raised rand randint random randrange range
    ratio rational raw rawdata rawinput rawsock rbrace rdivmod rdonly rdwr read readable readall readbuffer
    reader readers readframes reading readinto readline readlines readlink readonly ready real realpath reason
    rebuild received recognized record records rectangle recursion recursive recv recvfrom recvmsg redirect
    reduce reduction ref reference refresh regex regexp register registered registry reinit reject rel
    relative release relief reload relpath rem remainder remaining remote removals remove removed removeprefix
    rename rep reparse repeat repl replace reply report reported repr reprlib req reqheight request requested
    requests required requires res reserved reset resize resizemode resolve resolved resolver resource
    resources resp response responses rest restore result results resume ret retry return returncode retval
    reuse reuseaddr reuseport reverse reversed rewind rfc rfile rfind rfloordiv rgb rglob ridge right
    rightshift rindex rjust rmdir rmod rmtree rmul root rootnode rootx rooty ror rotate round row rowconfigure
    rows rpar rpartition rpow rshift rsplit rstrip rsub rtruediv rule rules run runcall runctx runner running
    runpy runtime rxor safe same samefile samestat sample sampwidth sanitize save saved sax scale scan scandir
    scanner scheduled schema scheme scls scm screen screenheight screenwidth script scrollbar scrolled search
    sec second seconds secs section sections secure security see seek seekable seen segment segments sel
    select selected selection selector selectors self sem semaphore semi send sendall sendfile sendmsg sendto
    sent sentinel sentinels sep separator separators seps seq sequence sequences serve server service serving
    session set setattr setblocking setcomptype setdefault setframerate setheading setitem setlocale setmode
    setnchannels setnframes setparams setpos setsampwidth setsockopt setstate setter settimeout settings
    settrace setup setworldcoordinates setx sety sha shadowed shallow shape shapesize shared sharer shell
    shift shim shlex shm short shorten should show showwarning shut shutdown shutil sibling side sig sigint
    sigmask sign signal signals signature signed signum sigterm simple simplefilter sin single singledispatch
    sio site size sizehint sizeof skip skipkeys skipped slash sleep slice slots smtp snapshot sock sockaddr
    socket socketpair socketserver socktype soft sol soon sort sorted soundpos source sourceless space spaces
    span spawn spawning spawnv spec special specials specified speed split splitdrive splitext splitlines
    splitlist splitroot splitter splituser sql sqlite sqrt src sre ssl sslcontext sslproto ssock stack
    stacklevel standalone standard star starmap start started startpos starts startswith starttls stat state
    statement states static staticmethod statistics stats status std stderr stdin stdlib stdout stem step
    sticky still stmt stop stopped store str strclass stream streamreader streams streamwriter strerror
    strftime strict string strings strip stripped strong strptime strs struct structure sts stuff style sub
    subclass subclasscheck subclasses subclasshook subdir subdirs subject submit submodule submodules subparts
    subpattern subprocess subscript subsequent subset subst substitute subtest subtype success successful
    suffix suffixes suite sum summarize summary super support supported supports suppress surrogates symbol
    symbols symlink symlinks syms sync synchronize syntax sys sysconf sysconfig sysid system tab table tables
    tabs tabsize tag tagname tail take taken target targetpath task tasks tau tcgetattr tcl tcp tcsaflush
    tcsetattr tear tell temp tempdir tempfile template temporary term terminal terminate terminator test
    testmod tests text textwrap the thing third this thousands thread threading threads threadsafe three
    threshold through throw tid tilde time timedelta timegm timeout timeouts timer timestamp timetuple
    timezone timezones title tkinter tls tmp tobytes today todo tok token tokenize tokenizer tokens toks too
    tool toordinal top topdown topics toplevel total touch trace traceback tracer tracing tracker trailer
    trailers trailing trans transfer transform transition translate transp transport transports traversable
    traversal traverse tree triple trsock true truediv trunc truncate try tspecials tstr tty ttype tup tuple
    turtle txt typ type typecode typed typename types typing tzinfo tzname tzpath ubyte udp uid uint ulong
    ulonglong uname unbind uncancel undecodable undefined undo unencoded unescape unexpected unfinished uni
    unicode unicodedata unified union unique unit units unittest universal unix unixfrom unknown unless unlink
    unlocked unpack unparse unparsed unquote unregister unsafe unset unsupported until unused unwrap update
    updated upgrade upper urandom uri url urljoin urllib urlopen urlparse urlsplit urlunparse urlunsplit usage
    use used usedforsecurity usegmt user username ushort using utc utf util utils utime uuid val valid
    validate validation vals value values var varargs variable variables variant varkeywords varnames vars
    vbar ver verbose verbosity verify version versions view virtual visibility visible visit visitor void wait
    waiter waiters waiting waitpid waitstatus waittime wakeup walk want warn warning warnings warnoptions was
    watcher water wchar weak weakref weakrefset webbrowser week weekday weekdayname weight welcome wfile what
    wheel when whence where which while white whitespace whole why widget width wildcard win winapi window
    windows winerror winfo winner winreg winver with withdraw wnohang word words work worker workers wrap
    wrapped wrapper wraps writable write writeframes writeframesraw writelines writer writes writing written
    wrong wronly wsgi xml xmlns xmlreader xmlrpc xor xview year yes yield yview zero zeros zfill zip zipfile
    zlib zone
""".split())
