"""Generate privacy_guard/core/code_words.py: the words developers build identifiers from.

File names are spelled with the same words as identifiers (per_channel.py, loss_meta.py),
and the INSEE index lists many of them as given or family names. The words are measured
rather than listed by hand: every part of an identifier (snake_case and camelCase split)
in the Python standard library, kept when it appears in at least MIN_FILES modules so a
person's name met once in an identifier does not become a code word.

Only identifiers are read, never comments or strings, where authors' names appear.

Usage: python tools/build_code_words.py   (the interpreter's own standard library is read)
"""

from __future__ import annotations

import collections
import io
import platform
import re
import sysconfig
import textwrap
import tokenize
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1]
OUTPUT = PROJECT / "privacy_guard" / "core" / "code_words.py"
MIN_FILES = 3
# The parts of an identifier: Words, words and ACRONYMS.
_WORD = re.compile(r"[A-Z]?[a-z]+|[A-Z]+(?![a-z])")
# Test suites and IDLE are not library code; site-packages is third-party.
_SKIPPED_DIRECTORIES = frozenset({"test", "tests", "idlelib", "site-packages", "__pycache__"})

HEADER = '''"""Words developers build identifiers and file names from. Generated, do not edit.

Generated by tools/build_code_words.py from the identifiers of the Python {version}
standard library ({count} words, each in at least {min_files} modules). The file-name
detector never takes them for a given or family name.
"""

CODE_WORDS = frozenset("""
'''


def identifier_words(source: str) -> set[str]:
    words = set()
    try:
        for token in tokenize.generate_tokens(io.StringIO(source).readline):
            if token.type == tokenize.NAME:
                words.update(part.lower() for part in _WORD.findall(token.string) if len(part) >= 3)
    except (tokenize.TokenError, SyntaxError):
        pass  # A module the tokenizer rejects keeps the words read so far.
    return words


def library_modules(stdlib: Path):
    for path in sorted(stdlib.rglob("*.py")):
        if not _SKIPPED_DIRECTORIES.intersection(path.relative_to(stdlib).parts):
            yield path


def code_words(stdlib: Path) -> list[str]:
    modules_per_word = collections.Counter()
    for path in library_modules(stdlib):
        modules_per_word.update(identifier_words(path.read_text(encoding="utf-8", errors="replace")))
    return sorted(word for word, modules in modules_per_word.items() if modules >= MIN_FILES)


def render(words: list[str]) -> str:
    body = textwrap.fill(" ".join(words), width=110, initial_indent="    ", subsequent_indent="    ",
                         break_on_hyphens=False)
    header = HEADER.format(version=platform.python_version(), count=len(words), min_files=MIN_FILES)
    return header + body + '\n""".split())\n'


def main() -> None:
    words = code_words(Path(sysconfig.get_paths()["stdlib"]))
    OUTPUT.write_text(render(words), encoding="utf-8", newline="\n")
    print(f"{len(words)} words written to {OUTPUT.relative_to(PROJECT).as_posix()}")


if __name__ == "__main__":
    main()
